### ISSUE TITLE
Failed to build BR for NUCLEO_F429ZI

### ISSUE THREAD

**Issue by artokin** [ARMmbed/nanostack-border-router#113]
Border router builds for target NUCLEO_F429ZI are failing in mbed-os-5.9.0-oob branch because of linker errors:

mbed compile -t GCC_ARM -m NUCLEO_F429ZI -j 0 --app-config ./configs/Thread_Atmel_RF.json
...
> Compile [100.0%]: test_env.cpp
> Link: nanostack-border-router
> BUILD/NUCLEO_F429ZI/GCC_ARM/source/border_router_main.o: In function `backhaul_driver_init':
> /home/arto/github/nanostack-border-router/./source/border_router_main.cpp:154: undefined reference to `arm_eth_phy_device_register'
> collect2: error: ld returned 1 exit status
> [ERROR] BUILD/NUCLEO_F429ZI/GCC_ARM/source/border_router_main.o: In function `backhaul_driver_init':
> /home/arto/github/nanostack-border-router/./source/border_router_main.cpp:154: undefined reference to `arm_eth_phy_device_register'
> collect2: error: ld returned 1 exit status
> 
> [mbed] ERROR: "/usr/bin/python" returned error code 1.
> [mbed] ERROR: Command "/usr/bin/python -u /home/arto/github/nanostack-border-router/mbed-os/tools/make.py -t GCC_ARM -m NUCLEO_F429ZI --source . --build ./BUILD/NUCLEO_F429ZI/GCC_ARM --app-config ./configs/Thread_Atmel_RF.json -j 0" in "/home/arto/github/nanostack-border-router"

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2593

**Comment by adbridge** [comment]
@kjbracey-arm please investigate

**Comment by kjbracey-arm** [comment]
If I understand everything correctly, to avoid a start-up error being consistently hit in CI @artokin has switched the config back to using old-style Nanostack drivers rather than EMAC drivers.

However, the STM32 Nanostack driver is no longer compatible with 5.9 and has been removed, which means that Nucleo builds are no longer available with this repo's default config.

I believe @artokin was going to accept this state with only K64F Ethernet being available as a 5.9.0 known issue.

Is should be possible to clear this up fully by switching back to EMAC config if https://github.com/ARMmbed/mbed-os/pull/7121 clears the init problem and there are no other problems. (Not sure if he had other blocking memory usage.)  Is that likely to be landable for 5.9.0?

Alternatively maybe could have a target override so only K64F uses the Nanostack driver and other targets use EMAC. But they're still liable to crash on startup on a busy (such as CI) network without the 7121 patch.

**Comment by adbridge** [comment]
@artokin @kjbracey-arm I suspect this will have to go as a known issues against the example for 5.9 and then the fixes can come into 5.9.1 (which will land about a week after 5.9.0).

**Comment by artokin** [comment]
This issue added to "known issues" in PR https://github.com/ARMmbed/nanostack-border-router/pull/118

**Comment by artokin** [comment]
PR https://github.com/ARMmbed/nanostack-border-router/pull/121 enabled EMAC feature. The application can be compiled again with NUCLEO_F429ZI. 
Closing issue.
