### ISSUE TITLE
Commissioning app support?

### ISSUE THREAD

**Issue by ubx-caloca** [ARMmbed/nanostack-border-router#125]
I imported the nanostack-border-router in the Online Mbed Compiler, copied the contents of /config/Thread_Atmel_RF.json to mbed_app.json, changed the radio-type to MCR20 (I'm using a K64F + MCR20), set the rf-channel to 26 and backhaul-driver to ETH.  Then I flashed the bin image, connected the Ethernet cable, and ran the Border Router. I notice that it creates the Thread network, however when opening the Thread Commissioning App it not appearing in the available BRs list. My Wifi where the smartphone is connected has connection to the Ethernet connection, I had used other vendor BR (e.g. Openthread) and it has worked before.

Does the nanostack-border-router project supports commissioning using the app? If not, is there a way to manually commission a Thread joiner to the BR?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-2652

**Comment by artokin** [comment]
nanostack-border-router supports commissioning using the app. However, it requires IPv6 backbone in order to operate. 

Would you have any traces from the nanostack border router? It is tracing backhaul and mesh addresses in 20 seconds interval and global IPV6 address should be visible in the trace.

**Comment by artokin** [comment]
Here you can find more information about Thread commissioning: https://os.mbed.com/docs/v5.9/reference/mesh-tech.html#thread-commissioning

**Comment by ubx-caloca** [comment]
Thanks fo the info Artokin, I did follow the thread commissioning info that you mentioned. 

I'm attaching the debug output (Is this the traces that you asked?). I'm also attaching the mbed_app.json file that I used.

[ArmNoComm.txt](https://github.com/ARMmbed/nanostack-border-router/files/2181475/ArmNoComm.txt)

[mbed_app.json.log](https://github.com/ARMmbed/nanostack-border-router/files/2181481/mbed_app.json.log)

I tried it out with the Openthread Border Router and its detecting the BR with both IPv4 and IPv6 address.
![screenshot_20180710-101652_thread](https://user-images.githubusercontent.com/4306233/42527320-249097ea-842d-11e8-8338-4c155ff93426.jpg)

**Comment by artokin** [comment]
`mbed_app.json` looks good. Attached debug trace indicates that backbone does not have ULA/global IPv6 address. It is sending RS messages to backbone but it does not receive RA message where it can generate IPv6 address.
 
Would you please try to modify your wifi router settings so that it is in IPv6 only mode and assigns ULA/global prefix for the network? Preferably DHCP disabled is possible.

Currently nanostack-border-router does not enable border router functionality to mesh unless there is a ULA/global prefix available in the backbone.

cc: @mikter , @karsev , @deepakvenugopal

**Comment by artokin** [comment]
One possible solution would be to allow border router to generate prefix itself. Would you please try to set `backhaul-dynamic-bootstrap": false,` in the `mbed_app.json` and try again?
This configuration option is targeted for operating in backhaul that does not have IPv6 available.

**Comment by ubx-caloca** [comment]
Thanks Artokin, changing the backhaul-dynamic-bootstrap": false works, I can now see the BR in the app. 

Regarding the commissioner passphrase, the /config/Thread_Atmel_RF.json includes a pskc parameter set to a byte array, you do know what this the actual passphrase of that Pskc example value?

**Comment by artokin** [comment]
Excellent, the application passphrase is "Thread Network", more details [here](https://os.mbed.com/docs/v5.9/reference/mesh-tech.html#using-the-thread-commissioning-application).

**Comment by TuomoHautamaki** [comment]
Hi @ubx-caloca , we believe this issue is now solved and can be closed. Can you please confirm?

**Comment by ubx-caloca** [comment]
Yes Its working great. Thank you very much.
