### ISSUE TITLE
How to configure this for K64F and Wi-SUN

### ISSUE THREAD

**Issue by jwyune** [ARMmbed/nanostack-border-router#171]
Hi,

I'm trying to set up a Wi-SUN border router with K64F and STEVAL-FKI915V1. Note that for the router, I am using [this repository](https://github.com/ARMmbed/mbed-os-example-mesh-minimal).

[mbed_app.txt](https://github.com/ARMmbed/nanostack-border-router/files/3143970/mbed_app.txt)

The uploaded file is my mbed_app.json. Is this the only thing that I have to modify for what I'm trying to do? There isn't much available right now, so if anyone can help me get started, it would be very much appreciated. Thanks a lot.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTTHD-3483

**Comment by TuomoHautamaki** [comment]
Hi @jwyune,

We've tested S2-LP driver with X-Nucleo-S2868A1 RF expansion board. With this board we had following issue. You probably have the same issue.
_Default SPI SCLK pin configuration is D13. On X-Nucleo-S2868A1, resistor R6 must be soldered instead of R11. For more information, see user manual UM2405. https://www.st.com/resource/en/user_manual/dm00498153.pdf_

If this is not the issue, then please provide logs for us to analyse.

Regards,
Tuomo

**Comment by artokin** [comment]
Hello @jwyune ,

I hope your problem is solved when resistor is soldered to to RF expansion board and mbed-os-example-mesh-minimal is now compiled with command `mbed compile -t GCC_ARM -m NUCLEO_F429ZI --app-config ./configs/mesh_wisun_S2LP.json` and nanostack-border-router with command `mbed compile -t GCC_ARM -m K64F --app-config ./configs/Wisun_Stm_s2lp_RF.json`.

I'm closing this issue now. If you have any other issues, please don't hesitate to file a new issue.

BR,
Arto

**Comment by jwyune** [comment]
Thanks a lot!

**Comment by jwyune** [comment]
Thanks a lot. I have one more question, not so much related to Wi-SUN itself. Is it possible to imitate `--app-config` on Mbed Studio?

**Comment by artokin** [comment]
I'm still using other IDEs (Keil/IAR) and there `--app-config` can be used when exporting project. 

Personally I have not tried Mbed Studio yet. When looking at documentation in https://os.mbed.com/docs/mbed-studio/0.5/using-mbed-studio/configuring-build-tools-and-profiles.html it looks like it is using `mbed_app.json` from the application top level.  So by replacing the application top level `mbed_app.json` with your `Wi-SUN-xxx-.json` will at least work.
